def COLOR_MAP = [
    "SUCCESS": "good", // Corrected typo 'SUCCES' to 'SUCCESS'
    "FAILURE": "danger",   
]

pipeline {
    agent any
    tools {
        maven 'MAVEN3'
        jdk 'OracleJDK8'
    }
    environment {
      
        cluster = "vproapp-prod"
        service = "vproapp-prod-svc"


    } 
    stages {

        stage('Cleanup Workspace') {
            steps {
                 sh 'rm -rf build/ tmp/' // Adjust paths as necessary
            }
        }
      
        stage('Build') {
            steps {
                sh 'mvn -s settings.xml -U clean install -DskipTests'
            }
            post {
                success {
                    echo 'Now Archiving...'
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }
      
    stage("Deploy to ECS Prod") {
        steps {
            withAWS(credentials: "awscreds", region: "eu-central-1") {
            sh "aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment"
        }
    }
}


    post {
        always {
            echo 'Slack Notification'
            slackSend(
                channel: '#jenkinscicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL} "
            )
        }
    }
}



        
